-- Temperate + River probe. GENERATED by tools/build.py - do not edit by hand.
--
-- The stock temperate generator pointed at our own node tree: the stock graph
-- with the river layout taken from our scripted node.
-- The stock sliders are untouched and still work.
function data()
return { 
		nodeTree = "mapzilla_river_a.tree",
		climate = "::/climates/temperate/temperate.clima",
		desc = { 
			cargoTypeSet = { 
				cargoClassesExcluded = { },
				cargoClassesIncluded = { },
				cargoTypesExcluded = { },
				cargoTypesIncluded = { },
			},
			name = _("Temperate + River probe"),
		},
		editorOnly = false,
		order = 90,
		params = {
			{ 
				
				defaultIndex = 3,
				images = { },
				key = "oceans",
				name = _("Lakes"),
				tags = { },
				tooltip = _("Adjust the number of lakes on the map."),
				uiType = "Slider",
				valueIndices = { },
				values = {
					_("Sparse"),
					_("Scattered"),
					_("Medium"),
					_("Dense"),
					_("Packed"),
				},
				yearFrom = 0,
				yearTo = 0,
			},
			{ 
				
				defaultIndex = 3,
				images = { },
				key = "water",
				name = _("Rivers"),
				tags = { },
				tooltip = _("Adjust the number of rivers on the map."),
				uiType = "Slider",
				valueIndices = { },
				values = {
					_("Sparse"),
					_("Scattered"),
					_("Medium"),
					_("Dense"),
					_("Packed"),
				},
				yearFrom = 0,
				yearTo = 0,
			},
			{ 
				
				defaultIndex = 3,
				images = { },
				key = "mountains",
				name = _("Mountains"),
				tags = { },
				tooltip = _("Adjust the number and height of mountains on the map."),
				uiType = "Slider",
				valueIndices = { },
				values = {
					_("Sparse"),
					_("Scattered"),
					_("Medium"),
					_("Dense"),
					_("Packed"),
				},
				yearFrom = 0,
				yearTo = 0,
			},
		},
		previewSeed = "yQKiK",
		updateScript = { 
			fileName = "",
			params = { },
		},
	}
end
